direction_1=input("Enter a cardinal direction: ")
timeofday_1=input("Enter morning/noon/afternoon/sunset/dusk: ")
animal_1=input("Enter an animal: ")
greeting_1=input("Enter a greeting: ")
greeting_2=input("Enter a greeting-response: ")
discovery_1=input("Enter something that could be lost and later discovered in a faraway place: ")

print("To your ", direction_1, " is a deep dark forest. The trees are tall and the foliage is dense.")
print("A wind ripples through the trees. It reminds you of a dream.")
print("It is ", timeofday_1, ".")
print("A",animal_1, " emerges from behind a tree and approaches you.")
print("She says, ", greeting_1)
print("You respond ", greeting_2)
print("You explore the forest together and find a ", discovery_1, ".")
